blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.ArticleIndexView.as_view(), name='index'),
    path('new/', views.ArticleNewView.as_view(), name='new'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.ArticleEditView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='delete'),
    path('tags/<str:name>/', views.ArticleTagView.as_view(), name='tag_detail'),
    # 非同期いいね
    path('<int:pk>/like/', views.ArticleLikeView.as_view(), name='like_detail'),
    # 検索機能
    path('search/', views.SearchView.as_view(), name='search'),
    path('cart/', views.ArticleInCartView.as_view(), name='cart'),
    path('purchase/', views.ArticlePurchaseView.as_view(), name='purchase'),
    # フォロー
    path('follow/<int:pk>', views.FollowView.as_view(), name='follow'),
    # DM
    path('dm/index', views.DMIndexView.as_view(), name="dm_index"),
    path('dm/<int:pk>', views.DMDetailView.as_view(), name="dm_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# キャッシュ
from django.views.decorators.cache import cache_page

from mysite import views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('demo/', include('demo.urls')),
    path('', views.TopView.as_view(), name='top'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]
urlpatterns += static(settings.MEDIA_URL,
                document_root=settings.MEDIA_ROOT)

demo/urls.py
from django.urls import path

# キャッシュ
from django.views.decorators.cache import cache_page

from . import views

app_name = 'demo'
urlpatterns = [
    path('pay/', views.PayView.as_view(), name='pay'),
    path('cache_test/', cache_page(30)(views.CacheTestView.as_view()), name='cache'),
]

templates/snippets/articles_index.html
<div class="card h-100" id="article-card-{{ article.id }}" style="display:none;">
    <a href="{% url 'blog:detail' article.id %}">
        <div id="carouselIndicators{{ article.id }}" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                {% for / in article.image.all %}
                <button type="button" data-bs-target="#carouselIndicators{{ article.id }}" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}" aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}"></button>
                {% endfor %}
            </div>
            <div class="carousel-inner">
                {% for image in article.image.all %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="10000000000">
                    <img src="{{ image.image.url }}" class="d-block w-100 article_image img-thumbnail">
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators{{ article.id }}" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators{{ article.id }}" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden"></span>
            </button>
        </div>
        <div class="card-body">
            <a href="{% url 'author' pk=article.author.id %}" class="text-decoration-none text-dark">
                <img src="{{ article.author.profile.image.url }}" alt="" class="col-2 article_profile_image rounded-circle border border-secondary">
                {{ article.author.profile.username }}
                <span class="text-danger"></span>
                <span class="small text-muted">
                    {% if request.user == article.author %}
                    (あなた)
                    {% endif %}
                </span>
            </a>
            <h5 class="card-title mt-3">{{ article.title }}</h5>
            <p class="card-text">{{ article.text|truncatechars:30 }}</p>
            <div class="d-flex">
                <i class="bi bi-suit-heart mb-1 me-1"></i>
                {{ article.like_count }}
                <i class="ms-1 bi bi-chat-left-dots mb-2 me-1"></i>
                {{ article.comment_count }}
                <p class="ms-1">閲覧数 {{ article.view_total_count }}</p>
            </div>
            <div class="small text-muted">
                {% if article.id in uset_item_ids %}
                記事を販売中：価格{{ article.price }}円 購入済
                {% elif article.sell_flag and article.price != 0 %}
                記事を販売中：価格{{ article.price }}円
                {% else %}
                無料
                {% endif %}
            </div>
            {% if article.sell_flag and article.price != 0 and not article.author == request.user and not article.id in uset_item_ids %}
                {% if article.id in purchased_article_ids and article.id in user_items %}
                <a href="{% url 'blog:cart' %}?article_id={{ article.id }}&delete=True" type="button" class="btn btn-primary">カートから外す</a>
                {% else %}
                <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#purchaseModal{{ article.pk }}">
                    カートにいれる
                </button>
                {% endif %}
            {% include "snippets/modal_purchase.html" %}
            {% endif %}
            <p class="text-danger">記事の星5評価</p>
            <small class="text-muted">投稿日 {{ article.created_at }}</small>
        </div>
    </a>
</div>

{% comment %} 最初の数秒間はデモを表示 {% endcomment %}
<div class="card h-100 placeholder-glow" id="placeholder-card-{{ article.id }}" aria-hidden="true">
    <div alt="" class="article_image_placeholder mb-3 bg-secondary placeholder img-thumbnail"></div>
    <div class="card-body">
        <img alt="" class="col-2 article_profile_image placeholder rounded-pill">
        <span class="placeholder col-8 rounded-pill"></span>
        <h5 class="card-title mt-3 placeholder col-7 rounded-pill"></h5>
        <p class="mt-1 card-text placeholder col-10 rounded-pill"></p>
        <div class="d-flex mt-3 mb-3">
            <i class="me-1 placeholder col-1 rounded-pill"></i>
            <i class="ms-1 me-1 placeholder col-1 rounded-pill"></i>
            <i class="ms-1 me-1 placeholder col-2 rounded-pill"></i>
        </div>
        <div class="small text-muted">
            {% if article.id in uset_item_ids %}
            <span class="placeholder col-8 rounded-pill"></span>
            {% elif article.sell_flag and article.price != 0 %}
            <span class="placeholder col-7 rounded-pill"></span>
            {% else %}
            <span class="placeholder col-5 rounded-pill"></span>
            {% endif %}
        </div>
        {% if article.sell_flag and article.price != 0 and not article.author == request.user and not article.id in uset_item_ids %}
            {% if article.id in purchased_article_ids and article.id in user_items %}
            <a href="{% url 'blog:cart' %}?article_id={{ article.id }}&delete=True" type="button" class="btn btn-primary placeholder col-8 rounded-pill"></a>
            {% else %}
            <button type="button" class="btn btn-outline-success placeholder col-8 rounded-pill" data-bs-toggle="modal" data-bs-target="#purchaseModal{{ article.pk }}"></button>
            {% endif %}
        {% include "snippets/modal_purchase.html" %}
        {% endif %}
        <small class="text-muted placeholder col-7 rounded-pill"></small>
    </div>
</div>


{% comment %} デモを非表示にし、本来の記事を表示する {% endcomment %}
<script>
    setTimeout(function() {
        document.querySelectorAll('[id^="placeholder-card-"]').forEach(function(el) {
            el.style.display = 'none';
        });
        document.querySelectorAll('[id^="article-card-"]').forEach(function(el) {
            el.style.display = 'block';
        });
    }, 1000);
</script>

templates/snippets/base_auth.html
<!doctype html>
<html lang="en">
    <head>
        {% include "snippets/head.html" %}
    </head>
    <body>
        <div class="message-container" style="min-height: 50px; position: fixed; width: 100%; top: 70px;">
            {% include "snippets/messages.html" %}
        </div>
        </div>
        <div class="vh-100 d-flex align-items-center justify-content-center bg-light">
            {% block content %}{% endblock %}
        </div>

    </body>
</html>

templates/snippets/comment.html
<div class="">
    <h3 class="h6">コメント</h3>
    <div class="list-group">
        {% for comment, time_ago in comments_with_time %}
            <div class="list-group-item list-group-item-action p3 rounded-0">
                <p class="m-0">
                    <small>{{ comment.user.profile.username }}</small>
                </p>
                <p class="m-0">{{ comment.comment }}</p>
                <div class="m-0 d-flex">
                    <small>{{ time_ago }}</small>
                    {% if comment.user == request.user %}
                    <a href="#" class="text-decoration-none text-secondary ms-3">編集する</a>
                    {% endif %}
                </div>
                {{ comment.tex }}
            </div>
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
        <form action="{% url 'blog:detail' pk=article.id %}" method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label for="comment_textarea">コメント投稿</label>
                <textarea id="comment_textarea" name="comment" class="rounded-0 bg-light form-control"></textarea>
            </div>
            <div class="text-right">
                <button class="btn btn-sm btn-outline-success" type="submit">
                    コメントする
                </button>
            </div>
        </form>
    {% else %}
        コメントするには、<a href="{% url 'login' %}">ログイン</a>が必要です。
    {% endif %}
</div>

templates/snippets/footer.html
{% load static %}
<div class="footer-padding-top"></div>
<footer class="border-top py-1 text-center bg-light pt-3 pb-3" id="footer">
    <a href="/" class="text-decoration-none">トップに戻る</a>
</footer>

<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->

    <script>
        window.addEventListener('scroll', function() {
            // ページ全体の高さ
            const documentHeight = document.documentElement.scrollHeight;

            // 現在のスクロール位置 + 画面の高さ
            const scrollPosition = window.scrollY + window.innerHeight;

            // スクロール位置がページの最下部に到達したか確認
            if (scrollPosition >= documentHeight) {
                // フッターを表示する
                footer.style.opacity = '1';
                footer.style.transition = 'opacity 0.5s ease';
            } else {
                // フッターを非表示にする
                footer.style.opacity = '0';
                footer.style.transition = 'opacity 0.5s ease';
            }
        });
    </script>

templates/snippets/head.html
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

<link rel="stylesheet" href="{% static 'css/style.css' %}?v=2024-06-02">

<title>Really Site</title>

templates/snippets/header.html
<div class="container">
    <header class="py-3">
        <div class="row flex-nowarp justify-content-center align-items-center">
            <div class="col-4 text-center">
                <h1 class="display-4 font-italic">
                    <a href="/" class="text-decoration-none text-secondary">ReallySite</a>
                </h1>
            </div>
        </div>
    </header>
</div>
<nav class="navbar navbar-expand bg-body-tertiary mb-2 bg-info pt-2 pb-2 mb-5">
    <div class="container container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}">ブログ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:purchase' %}">マイカート</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">お問い合わせ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mypage' %}">マイページ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#}">グループチャット</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#}">管理者の方</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        デモ一覧
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'demo:pay' %}">決済デモページ</a></li>
                        <li><a class="dropdown-item" href="{% url 'demo:cache' %}">キャッシュテスト</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:search' %}"><i class="bi bi-search"></i></a>
                </li>
            </ul>
        </div>
        {% if user.is_authenticated %}
        <form action="{% url 'logout' %}" method='post'>
            {% csrf_token %}
            <button class="btn btn-outline-secondary" type="submit">ログアウト</button>
        </form>
        {% else %}
            <a class="p-2 link-secondary" href="{% url 'login' %}">ログイン</a>
            <a class="p-2 link-secondary" href="{% url 'signup' %}">サインイン</a>
        {% endif %}
    </div>
</nav>

templates/snippets/like.html
{% comment %} <form action="{% url 'blog:detail' article.id %}" method='post'>
    {% csrf_token %}
    <button type='submit'>
        <input type="hidden" name='like_count' value='True'>
        {% if like_count > 0 %}
            <i class="bi bi-suit-heart-fill" style='color: red;'>
                <span>{{ like_count }}</span>
                <input type="hidden" name='like_delete', value='True'>
            </i>
            {% else %}
            <i class="bi bi-suit-heart">
                <span>{{ like_count }}</span>
            </i>
        {% endif %}
    </button>
</form> {% endcomment %}

<div class="d-inline my-1">
    <button type='button' id='like_btn' class="btn btn-outline-danger">
        {% if like_count > 0 %}
            <i class="bi bi-suit-heart-fill text-danger" id="like-for-post-icon"></i>
        {% else %}
            <i class="bi bi-suit-heart" id="like-for-post-icon"></i>
        {% endif %}
        <span id="like_count">{{ like_count }}件のいいね</span>
    </button>
</div>

<script>
    // ページの内容が扱えるようになったら
    window.addEventListener("DOMContentLoaded", (e) => {

        var likeBtn = document.getElementById('like_btn');

        // いいねボタンがクリックされたら
        likeBtn.addEventListener('click', (e) => {
            // 送信先URL
            // var url = "blog/{{ article.id }}/like";
            var url = "{% url 'blog:like_detail' article.id %}";
            // csrf_tokenの取得
            var csrfToken = getCookie("csrftoken")
            // 送信したいデータ
            var data = {
                article_pk: "{{ article.id }}",
            }

            // 送信機能
            fetch(url, {
                method: "POST",
                credentials: 'same-origin',
                headers: {
                    "Content-Type": "application/json",
                    "X-Requested-With": "XMLHttpRequest",
                    "X-CSRFToken": csrfToken,
                },
                body: JSON.stringify(data),
            })
            // viewsから送られてくるJsonResponseを受け取る
            // Response => Response.json()でJSONにする
            .then(Response => Response.json())
            .then(data => {
                if (data["message"] == "success") {
                    console.log(Response);
                    var LikeCount = document.getElementById("like_count");
                    var icon = document.getElementById('like-for-post-icon')

                    // いいねの数を上書き
                    LikeCount.textContent = data['like_count'] + '件のいいね'
                    if (data["method"] == "create") {
                        icon.classList.remove('bi-suit-heart');
                        icon.classList.add('bi-suit-heart-fill', 'text-danger');
                    } else {
                        icon.classList.remove('bi-suit-heart-fill', 'text-danger');
                        icon.classList.add('bi-suit-heart');
                    }
                    icon.id = 'like-for-post-icon'
                }else {
                    console.log('errorです。')
                }
            })
            // エラーが発生したら
            .catch((error) => {
                console.log(error)
            });

        }, false);
    }, false);

// cookieのキーがあれば取得
// 指定した名前 (name) のクッキーを探し、その値をデコードして返す
function getCookie(name) {
    if (document.cookie && document.cookie != "") {
        for (var cookie of document.cookie.split(';')) {
            var [key, value] = cookie.trim().split("=");
            if (key == name) {
                return decodeURIComponent(value);
            }
        }
    }
}

</script>

templates/snippets/messages.html
{% comment %} メッセージの内容 {% endcomment %}
{% for message in messages %}
    <nav class="py-2 {{ message.tags }}">
        <div class="container text-center p-1">
            {{ message }}
        </div>
    </nav>
{% endfor %}

templates/snippets/modal_purchase.html
<!-- Modal -->
<div class="modal fade" id="purchaseModal{{ article.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">記事の購入</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row mb-3">
                    <span class="mb-1">記事名</span>
                    <h5 class="blog-post-title ms-2">{{ article.title }}</h5>
                </div>
                <div class="row mb-3">
                    <span class="mb-1">記事のテキスト</span>
                    <span class="blog-post-title ms-2">{{ article.text|truncatechars:20 }}（全{{ article.text|length }}文字）</span>
                </div>
                <div class="row mb-3">
                    <span class="mb-1">価格</span>
                    <span class="blog-post-title ms-2">￥{{ article.price }}円</span>
                </div>
                <div class="row mb-3 small text-muted">
                    <span class="blog-post-meta">作成日時：{{ article.created_at }}</span>
                    <span class="blog-post-meta">最終更新日時：{{ article.updated_at }}</span>
                </div>
            </div>
            <div class="modal-footer d-flex justify-content-evenly">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">戻る</button>
                <a href="{% url 'blog:cart' %}?article_id={{ article.id }}" type="button" class="btn btn-primary">カートに入れる</a>
            </div>
        </div>
    </div>
</div>

templates/snippets/pagination.html
<nav class="blog-pagination d-flex justify-content-center">
    <div class="pagination">
        <span class="step-links">
            {% if paginator_articles.has_previous %}
            <a class="btn btn-outline-primary" href="?page={{ paginator_articles.previous_page_number }}">＜</a>
            {% endif %}
            <span class="m-2 current">
                {{ paginator_articles.number }} / {{ paginator_articles.paginator.num_pages }}
            </span>

            {% if paginator_articles.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ paginator_articles.next_page_number }}">＞</a>
            {% endif %}
        </span>
    </div>
</nav>

templates/snippets/sideber.html
{% load static %}
{% load cache %}

{% cache 86400 siedbar %}

<aside class="col-md-4">
    <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">
            ふじサンについて
        </h4>
        <p class="mb-0">ようこそMy講座へ！</p>
    </div>

    <figure class="figure">
        <img src="{% static 'mysite/IMG_1131.jpg' %}" alt="" class="figure-img img-fluid rounded">
        <figcaption class="figure-caption text-center font-italic small">
            <a class="text-muted" href="#">リンク先はありません。</a>
        </figcaption>
    </figure>

    <figure class="figure">
        <img src="{% static 'mysite/fruit-8283261_640.jpg' %}" alt="" class="figure-img img-fluid rounded">
        <figcaption class="figure-caption text-center font-italic small">
            <a class="text-muted" href="https://pixabay.com/ja/photos/%E3%83%95%E3%83%AB%E3%83%BC%E3%83%84-%E3%82%B6%E3%82%AF%E3%83%AD-%E3%82%B8%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%BC-8283261/" target="_blank" rel="noopener noreferrer">フルーツ-ザクロ-ジューシー</a>
        </figcaption>
    </figure>
</aside>

{% endcache  %}