blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.ArticleIndexView.as_view(), name='index'),
    path('new/', views.ArticleNewView.as_view(), name='new'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.ArticleEditView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='delete'),
    path('tags/<str:name>/', views.ArticleTagView.as_view(), name='tag_detail'),
    # 非同期いいね
    path('<int:pk>/like/', views.ArticleLikeView.as_view(), name='like_detail'),
    # 検索機能
    path('search/', views.SearchView.as_view(), name='search'),
    path('cart/', views.ArticleInCartView.as_view(), name='cart'),
    path('purchase/', views.ArticlePurchaseView.as_view(), name='purchase'),
    # フォロー
    path('follow/<int:pk>', views.FollowView.as_view(), name='follow'),
    # DM
    path('dm/index', views.DMIndexView.as_view(), name="dm_index"),
    path('dm/<int:pk>', views.DMDetailView.as_view(), name="dm_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# キャッシュ
from django.views.decorators.cache import cache_page

from mysite import views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('demo/', include('demo.urls')),
    path('', views.TopView.as_view(), name='top'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]
urlpatterns += static(settings.MEDIA_URL,
                document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from typing import Any
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model

CHARGE_TYPE = (
    (0, '課金なし'),
    (1, 'クレジットカード決済'),
)

def upload_article_image_to(instance, filename):
    user_id = 'UserID:' + str(instance.article.author.id)
    article_id = 'ArticleID:' + str( instance.article.id)
    return os.path.join('article', 'images', user_id, article_id, filename)


class ArticleTag(models.Model):
    slug = models.CharField(verbose_name='SLUG', unique=True, max_length=20, primary_key=True)
    name = models.CharField(verbose_name='タグ名', unique=True, max_length=20)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'タグ'
        db_table = 'article_tag'

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(verbose_name='タイトル', default='タイトルです。', max_length=30, null=False, blank=False)
    text = models.TextField(verbose_name='テキスト', default='テキストです。', max_length=255, null=False, blank=False)
    author = models.ForeignKey(get_user_model(), verbose_name='作成者', on_delete=models.CASCADE, related_name='articles')
    tags = models.ManyToManyField(ArticleTag, verbose_name='タグ', related_name='articles')
    is_public = models.BooleanField(verbose_name='公開', default=False)
    sell_flag = models.BooleanField(verbose_name='記事を販売', default=False)
    price = models.IntegerField(verbose_name='価格', default=0, blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = '記事'
        db_table = 'article'

    def __str__(self):
        return self.title



class Image(models.Model):
    image = models.ImageField(verbose_name='投稿画像', upload_to=upload_article_image_to)
    article = models.ForeignKey(Article, verbose_name="記事", on_delete=models.CASCADE, default='', related_name='image')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)


    class Meta:
        verbose_name_plural = '投稿画像'
        db_table = 'article_image'



class Comment(models.Model):
    comment = models.TextField(verbose_name='コメント', max_length='500')
    user = models.ForeignKey(get_user_model(), verbose_name='投稿者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'コメント'
        db_table = 'comment'

    def __str__(self):
        return self.comment


class ArticleLike(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='投稿者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='article_like')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'いいね'
        db_table = 'article_like'

    def __str__(self):
        return f'{ self.user } : {self.article}'


class Order(models.Model):

    ORDER_STATUS = (
        (0, '決済未登録'),
        (1, '決済完了'),
        (2, '決済失敗'),
        (200, '決済取り消し'),
    )

    user = models.ForeignKey(get_user_model(), verbose_name='ユーザー', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='order')
    price = models.IntegerField(verbose_name='価格', blank=True, null=True)
    charge_type = models.SmallIntegerField(verbose_name='課金タイプ', choices=CHARGE_TYPE, default=1)
    order_status = models.SmallIntegerField(verbose_name='決済ステータス', choices=ORDER_STATUS, default=1)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'ユーザー注文履歴'
        db_table = 'order'


class UserItem(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='ユーザー', on_delete=models.CASCADE, related_name='user_item')
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='user_item')
    charge_type = models.SmallIntegerField(verbose_name='課金タイプ', choices=CHARGE_TYPE, default=1)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta():
        verbose_name_plural = 'ユーザー購入商品'
        unique_together = ('user', 'article')
        db_table = 'user_item'

class ViewCount(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='ユーザー', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='view_count')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = '記事の閲覧カウント'
        db_table = 'view_count'
        indexes = [
            models.Index(fields=['article', 'created_at']),
        ]

    @classmethod
    def create_view_count(cls, user, article):
        if user != article.author:
            # 存在していなかったら新規で作成し、存在していたらレコードを返す
            cls.objects.get_or_create(user=user, article=article)
        view_count = cls.objects.filter(article=article).count()
        return view_count


class Follow(models.Model):
    follower = models.ForeignKey(get_user_model(), verbose_name="フォローしたユーザー", related_name='following', on_delete=models.CASCADE)
    followed = models.ForeignKey(get_user_model(), verbose_name="フォローされたユーザー", related_name='followers', on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)

    class Meta:
        verbose_name_plural = 'フォロー'
        db_table = 'user_follow'
        unique_together = ('follower', 'followed')

    # def __init__(self):
    #     return f'{self.follower} follows {self.followed}'

mysite/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver

from mysite.models.profile_models import Profile


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        # ユーザーがemailを持ってなかったらエラーを吐かせる
        if not email:
            raise ValueError('User must have an email address（ユーザー登録にはemailが必須です。）')
        user = self.model(
            email = self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    # unique=Trueで一意のメールアドレスしか受け付けない
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


# ユーザー（User）が作成された直後（post_save）に以下の関数を処理する
# Udemyの64
@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs['created']:

        Profile.objects.create(user=kwargs['instance'])

mysite/models/profile_models.py
import os

from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings


def upload_image_to(instance, filename):
    user_id = str(instance.user.id)
    return os.path.join('profile_images', user_id, filename)

PREFECTURE_CHOICE = (
    (0, '選択なし'),
    (1, '北海道'),
    (2, '青森'),
    (3, '岩手'),
    (4, '宮城'),
    (5, '秋田'),
    (6, '山形'),
    (7, '福島'),
    (8, '茨城'),
    (9, '栃木'),
    (10, '群馬'),
    (11, '埼玉'),
    (12, '千葉'),
    (13, '東京'),
    (14, '神奈川'),
    (15, '新潟'),
    (16, '富山'),
    (17, '石川'),
    (18, '福井'),
    (19, '山梨'),
    (20, '長野'),
    (21, '岐阜'),
    (22, '静岡'),
    (23, '愛知'),
    (24, '三重'),
    (25, '滋賀'),
    (26, '京都'),
    (27, '大阪'),
    (28, '兵庫'),
    (29, '奈良'),
    (30, '和歌山'),
    (31, '鳥取'),
    (32, '島根'),
    (33, '岡山'),
    (34, '広島'),
    (35, '山口'),
    (36, '徳島'),
    (37, '香川'),
    (38, '愛媛'),
    (39, '高知'),
    (40, '福岡'),
    (41, '佐賀'),
    (42, '長崎'),
    (43, '熊本'),
    (44, '大分'),
    (45, '宮崎'),
    (46, '鹿児島'),
    (47, '沖縄')
)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name='ユーザー', unique=True, on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(verbose_name='ユーザー名', default='匿名ユーザー', max_length=50)
    zipcode = models.CharField(verbose_name='郵便番号', max_length=8, blank=True, null=True)
    prefecture = models.SmallIntegerField(verbose_name='都道府県',choices=PREFECTURE_CHOICE, default=0)
    city = models.CharField(verbose_name='市区町村', max_length=100, blank=True, null=True)
    address = models.CharField(verbose_name='住所', max_length=200, blank=True, null=True)
    image = models.ImageField(verbose_name='プロフィール画像', upload_to=upload_image_to, default='images/default.png', blank=True)
    follows = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='フォローしているユーザー', related_name='followed_by')
    is_public = models.BooleanField(verbose_name='プロフィールを公開', default=1)

    class Meta:
        verbose_name_plural = 'プロフィール'
        db_table = 'profile'

    def __str__(self):
        return self.username

mysite/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models.profile_models import Profile

class UserCreateForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address',
            'image',
            'is_public',
        )

    def save(self, user_image=None, commit=True):
        profile = super().save(commit=False)
        # 新しい画像がアップロードされていない場合、既存の画像を保持
        if self.cleaned_data.get('image') == "images/default.png" and user_image != "images/default.png":
            profile.image = user_image.replace('media/', '')
        if commit:
            profile.save()
        return profile

templates/mysite/author.html
{% extends 'mysite/base.html' %}

{% load static %}

{% block content %}
<main class="container">
    <div class="row">
        <div class="col-md-8 m-auto">

            <div class="col-12">
                <img src="{{ user.profile.image.url }}" alt="" class="col-2 mb-1 profile_author_image rounded-circle border border-secondary">
                <span class="h5 ms-1">{{ user.profile.username }}</span>
                <div class="d-flex">
                    <div class="me-3 mt-1">
                        <a href="{% url 'blog:follow' pk=user.id %}?follower=True" class="text-decoration-none">フォロー数 {{ follows_count }}</a>
                        <a href="{% url 'blog:follow' pk=user.id %}" class="text-decoration-none">フォロワー数 {{ followed_count }}</a>
                    </div>
                    <form action="{% url 'blog:follow' user.id %}" method='post'>
                        {% csrf_token %}
                        {% if follow %}
                        <input type="hidden" name="delete" value=True>
                        <button class="btn btn-outline-info pt-1 pb-1 rounded-pill">フォロー解除</button>
                        {% else %}
                        <button class="btn btn-outline-info pt-1 pb-1 rounded-pill">フォローする</button>
                        {% endif %}
                    </form>
                </div>
                <a class="p-2 h5 link-secondary" href="#"><i class="bi bi-envelope"></i></a>
            </div>

            <hr>
            {% if user.profile.is_public %}
            <div class="row">
                <h4 class="mb-4">投稿記事</h4>
                <div class="col-10">
                    {% for article in public_artiles %}
                    <h5 class="blog-post-title">{{ article.title }}</h5>
                    <div class="blog-post-meta">
                        {{ article.created_at }}
                    </div>
                    <p class="text-danger">記事の星5評価と画像を追加したい</p>
                    <p>{{ article.text|truncatechars:30 }}</p>
                    <div class="d-flex">
                        <i class="bi bi-suit-heart mb-1 me-1"></i>
                        {{ article.like_count }}
                        <i class="ms-1 bi bi-chat-left-dots mb-2 me-1"></i>
                        {{ article.comment_count }}
                        <p class="ms-1">閲覧数 {{ article.view_total_count }}</p>
                    </div>
                    <div class="small text-muted">
                        {% if article.id in uset_item_ids %}
                        記事を販売中：価格{{ article.price }}円 購入済
                        {% elif article.sell_flag and article.price != 0 %}
                        記事を販売中：価格{{ article.price }}円
                        {% endif %}
                    </div>
                    {% if article.sell_flag and article.price != 0 and not article.author == request.user and not article.id in uset_item_ids %}
                        {% if article.id in purchased_article_ids and article.id in user_items %}
                        <a href="{% url 'blog:cart' %}?article_id={{ article.id }}&delete=True" type="button" class="btn btn-primary">カートから外す</a>
                        {% else %}
                        <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#purchaseModal{{ article.pk }}">
                            カートにいれる
                        </button>
                        {% endif %}
                    {% include "snippets/modal_purchase.html" %}
                    {% else %}
                    <a class="None-stretched-link" href="{% url 'blog:detail' article.id %}">続きを見る</a>
                    {% endif %}
                    <hr>

                    {% endfor %}
                </div>
            </div>
            {% else %}
            <p class="text-center pt-3">アカウントは非公開です</p>
            {% endif %}
        </div>
        {% comment %} {% include 'snippets/sideber.html' %} {% endcomment %}

    </div>
</main>

{% endblock %}

templates/mysite/base.html
<!doctype html>
<html lang="en">
    <head>
        {% include "snippets/head.html" %}
    </head>
    <body>
        {% include "snippets/header.html" %}
        {% include "snippets/messages.html" %}

        {% block content %}{% endblock %}

        {% include "snippets/footer.html" %}

    </body>
</html>

templates/mysite/contact.html
{% extends 'mysite/base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
        <h3 class="pb-4 mb-4 font-italic border-bottom">
            お問い合わせ
        </h3>

        <form class="row g-3" action={{ request.path }} method="post">
            {% csrf_token %}
            <div class="col-12">
                <label class="form-label">名前</label>
                <input type="text" class="form-control" id="id_name" name="name" placeholder="名前">
            </div>

            <div class="col-12">
                <label class="form-label">メールアドレス</label>
                <input type="email" class="form-control" id="id_email" name="email" placeholder="メールアドレス">
            </div>

            <div class="col-12">
                <label class="form-label">お問い合わせ内容</label>
                <textarea class="form-control" id='id_contact' name="contact" rows='4'></textarea>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary">送信</button>
            </div>
        </form>
    </div>
    {% include 'snippets/sideber.html' %}

    </div>
</main>

{% endblock %}

templates/mysite/index.html
{% extends "mysite/base.html" %}

{% block content %}

{% comment %} URLの書き方を省略して使える {% endcomment %}
{% url 'blog:index' as blog_index %}

<div class="container">
    <div class="p-4 p-md-5 mb-4 rounded bg-warning">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Django講座</h1>
            <p class="lead my-3">文章をかこう</p>
            <p class="lead mb-0">
                <a href="{% url 'blog:new' %}" class="font-weight-bold">新規作成</a>
            </p>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-12 m-auto text-center">
            <h3 class="shadow pb-2 pt-2 mb-3 bg-body-tertiary rounded">人気記事TOP2</h3>
        </div>
        {% for article in popular_articles %}
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row 
            mb-4 shadow-sm h-md-250 position-relative">
                {% include "snippets/articles_index.html" %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                最新記事TOP3
            </h3>
            <div class="card-deck row row-cols-1 row-cols-md-2 g-4 mb-3">
                {% for article in last_three_articles %}
                    {% include "snippets/articles_index.html" %}
                {% endfor %}
            </div>
            <nav class="blog-pagination">
                <a class="btn btn-outline-primary me-2" href="{{ blog_index }}">ブログ一覧はこちら</a>
                <a class="btn btn-outline-info" href="{% url 'blog:new' %}">新しい記事の作成</a>
            </nav>
        </div>
        {% comment %} サイドバー {% endcomment %}
        {% include "snippets/sideber.html" %}
    </div>
</main>

{% endblock %}

templates/mysite/mypage.html
{% extends 'mysite/base.html' %}

{% load static %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-lg-10 m-auto">
            <h3 class="pb-3 mb-1 font-italic">
                マイページ
            </h3>
            <div class="d-flex">
                <a href="{% url 'blog:dm_index' %}" class="p-2 h5 link-secondary"><i class="bi bi-envelope"></i></a>
                <div class="me-3 mt-2">
                    <span class="">投稿数 {{ user.articles.count }}</span>
                    <a href="{% url 'blog:follow' pk=user.id %}?follower=True" class="text-decoration-none text-dark">フォロー数 {{ follows_count }}</a>
                    <a href="{% url 'blog:follow' pk=user.id %}" class="text-decoration-none text-dark">フォロワー数 {{ followed_count }}</a>
                </div>
            </div>

            <form class="" method="post" enctype='multipart/form-data'>
                {% csrf_token %}

                <label for="id_image" class="form-label">プロフィール画像</label>
                <div class="ms-3 mb-2">
                    <img src="{{ user.profile.image.url }}" alt="" class="col-2 mb-1 profile_image rounded-circle border border-secondary" id="profileImage">
                    <input type="file" accept='image/*' name="image" class="form-control" id="id_image" required style="display:none;">
                </div>
                <div class="row">

                    <div class="col-12 mb-2">
                        <label class="form-label">ユーザー名（公開されます）</label>
                        <input type="text" class="form-control" id="id_username" name="username" placeholder="ユーザー名" value={{ user.profile.username }}>
                    </div>

                    <div class="col-md-2">
                        <label class="form-label">郵便番号</label>
                        <input type="text" class="form-control" id="id_zipcode" name="zipcode" placeholder="1234567" value={{ user.profile.zipcode }}>
                    </div>
                    <div class="col-md-4">
                        <label class="form-label">都道府県</label>
                        <select id="id_prefecture" name="prefecture" class="form-select">
                            {% for value, name in prefecture_choices %}
                                <option value="{{ value }}" {% if value == user.profile.prefecture %}selected{% endif %}>{{ name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label">市区町村</label>
                        <input type="text" class="form-control" id="id_city" name="city" placeholder="市区町村" value={{ user.profile.city }}>
                    </div>

                    <div class="col-12 mt-2">
                        <label class="form-label">住所</label>
                        <input type="text" class="form-control" id="id_address" name="address" placeholder="住所" value={{ user.profile.address }}>
                    </div>

                    <div class="col-12 ms-3 mt-3 form-check">
                        <input type="hidden" name='is_public' value=false>
                        <input type="checkbox" class="form-check-input" id="IsPublicCheck" name='is_public' value="1" {% if user.profile.is_public %}checked{% endif %}>
                        <label class="form-check-label" for="IsPublicCheck">プロフィールを公開しますか？</label>
                    </div>

                    <div class="col-12 mt-3">
                        <button type="submit" class="btn btn-success">保存</button>
                    </div>
                </div>
            </form>
            <hr>
            <div class="row">
                {% if true_public_artiles %}
                <h4 class="mb-2 text-center">公開中の記事</h4>
                <div class="card-deck row row-cols-1 row-cols-md-2 g-4 mb-3">
                    {% for article in true_public_artiles %}
                    <div class="col-lg-4 col-md-6 col">
                        {% include "snippets/articles_index.html" %}
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <h4 class="m-3 text-center">投稿はありません</h4>
                {% endif %}

                {% comment %} 非公開中の記事の参照 {% endcomment %}
                {% if false_public_artiles %}
                <p><a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">非公開中の記事を見る</a></p>
                <div class="row">
                    <div class="col">
                        <div class="collapse multi-collapse" id="multiCollapseExample1">
                            <div class="card-deck row row-cols-1 row-cols-md-2 g-4 mb-3">
                                {% for article in false_public_artiles %}
                                <div class="col-lg-4 col-md-6 col">
                                    {% include "snippets/articles_index.html" %}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</main>

<script>
    document.getElementById('profileImage').addEventListener('click', function() {
        document.getElementById('id_image').click();
    })
</script>

{% endblock %}

templates/mysite/pay.html
{% extends "mysite/base.html" %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                決済デモページ
            </h3>

            <p>charge情報：{{ charge }}</p>
            <p>ブランド{{ charge.card.brand }}</p>
            <p>****-****-****-{{ charge.card.last4 }}</p>
            <p>トークン情報：{{ card }}</p>

            <form action="" method='post'>
                {% csrf_token %}

                <script type='text/javascript' src="https://checkout.pay.jp" class="payjp-button" data-key="{{ public_key }}">
                </script>
            </form>

        </div>
        {% comment %} サイドバー {% endcomment %}
        {% include "mysite/snippets/sideber.html" %}
    </div>
</main>

{% endblock %}

templates/mysite/search.html
{% extends "mysite/base.html" %}

{% block content %}

<main class="container">
    <form action="post"></form>
</main>

{% endblock %}

templates/mysite/top.html
{% extends "mysite/base.html" %}

{% block content %}

{% comment %} URLの書き方を省略して使える {% endcomment %}
{% url 'blog:index' as blog_index %}

<div class="container">
    <div class="p-4 p-md-5 mb-4 rounded bg-warning">
        <div class="col-md-6 px-0">
            <h1 class="display-4 font-italic">Django講座</h1>
            <p class="lead my-3">文章をかこう</p>
            <p class="lead mb-0">
                <a href="{% url 'blog:new' %}" class="font-weight-bold">新規作成</a>
            </p>
        </div>
    </div>
</div>

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="col-12 m-auto text-center">
                <h3 class="shadow pb-2 pt-2 mb-3 bg-body-tertiary rounded">人気記事TOP4</h3>
            </div>
            <div class="col-lg-11 col-md-10 col-12 m-auto">
                <div class="card-deck row row-cols-1 row-cols-md-2 g-4 mb-3">
                {% for article in popular_articles %}
                    <div class="col-md-6 col-12">
                        {% include "snippets/articles_index.html" %}
                    </div>
                {% endfor %}
                </div>
            </div>
            <nav class="blog-pagination">
                <a class="btn btn-outline-primary me-2" href="{{ blog_index }}">ブログ一覧はこちら</a>
                <a class="btn btn-outline-info" href="{% url 'blog:new' %}">新しい記事の作成</a>
            </nav>
        </div>
        {% comment %} サイドバー {% endcomment %}
        {% include "snippets/sideber.html" %}
    </div>
</main>

{% endblock %}