blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('index/', views.ArticleIndexView.as_view(), name='index'),
    path('new/', views.ArticleNewView.as_view(), name='new'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.ArticleEditView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='delete'),
    path('tags/<str:name>/', views.ArticleTagView.as_view(), name='tag_detail'),
    # 非同期いいね
    path('<int:pk>/like/', views.ArticleLikeView.as_view(), name='like_detail'),
    # 検索機能
    path('search/', views.SearchView.as_view(), name='search'),
    path('cart/', views.ArticleInCartView.as_view(), name='cart'),
    path('purchase/', views.ArticlePurchaseView.as_view(), name='purchase'),
    # フォロー
    path('follow/<int:pk>', views.FollowView.as_view(), name='follow'),
    # DM
    path('dm/index', views.DMIndexView.as_view(), name="dm_index"),
    path('dm/<int:pk>', views.DMDetailView.as_view(), name="dm_detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# キャッシュ
from django.views.decorators.cache import cache_page

from mysite import views
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('demo/', include('demo.urls')),
    path('', views.TopView.as_view(), name='top'),
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]
urlpatterns += static(settings.MEDIA_URL,
                document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from typing import Any
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model

CHARGE_TYPE = (
    (0, '課金なし'),
    (1, 'クレジットカード決済'),
)

def upload_article_image_to(instance, filename):
    user_id = 'UserID:' + str(instance.article.author.id)
    article_id = 'ArticleID:' + str( instance.article.id)
    return os.path.join('article', 'images', user_id, article_id, filename)


class ArticleTag(models.Model):
    slug = models.CharField(verbose_name='SLUG', unique=True, max_length=20, primary_key=True)
    name = models.CharField(verbose_name='タグ名', unique=True, max_length=20)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'タグ'
        db_table = 'article_tag'

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(verbose_name='タイトル', default='タイトルです。', max_length=30, null=False, blank=False)
    text = models.TextField(verbose_name='テキスト', default='テキストです。', max_length=255, null=False, blank=False)
    author = models.ForeignKey(get_user_model(), verbose_name='作成者', on_delete=models.CASCADE, related_name='articles')
    tags = models.ManyToManyField(ArticleTag, verbose_name='タグ', related_name='articles')
    is_public = models.BooleanField(verbose_name='公開', default=False)
    sell_flag = models.BooleanField(verbose_name='記事を販売', default=False)
    price = models.IntegerField(verbose_name='価格', default=0, blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = '記事'
        db_table = 'article'

    def __str__(self):
        return self.title



class Image(models.Model):
    image = models.ImageField(verbose_name='投稿画像', upload_to=upload_article_image_to)
    article = models.ForeignKey(Article, verbose_name="記事", on_delete=models.CASCADE, default='', related_name='image')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)


    class Meta:
        verbose_name_plural = '投稿画像'
        db_table = 'article_image'



class Comment(models.Model):
    comment = models.TextField(verbose_name='コメント', max_length='500')
    user = models.ForeignKey(get_user_model(), verbose_name='投稿者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'コメント'
        db_table = 'comment'

    def __str__(self):
        return self.comment


class ArticleLike(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='投稿者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='article_like')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'いいね'
        db_table = 'article_like'

    def __str__(self):
        return f'{ self.user } : {self.article}'


class Order(models.Model):

    ORDER_STATUS = (
        (0, '決済未登録'),
        (1, '決済完了'),
        (2, '決済失敗'),
        (200, '決済取り消し'),
    )

    user = models.ForeignKey(get_user_model(), verbose_name='ユーザー', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='order')
    price = models.IntegerField(verbose_name='価格', blank=True, null=True)
    charge_type = models.SmallIntegerField(verbose_name='課金タイプ', choices=CHARGE_TYPE, default=1)
    order_status = models.SmallIntegerField(verbose_name='決済ステータス', choices=ORDER_STATUS, default=1)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'ユーザー注文履歴'
        db_table = 'order'


class UserItem(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='ユーザー', on_delete=models.CASCADE, related_name='user_item')
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='user_item')
    charge_type = models.SmallIntegerField(verbose_name='課金タイプ', choices=CHARGE_TYPE, default=1)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta():
        verbose_name_plural = 'ユーザー購入商品'
        unique_together = ('user', 'article')
        db_table = 'user_item'

class ViewCount(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name='ユーザー', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='記事', on_delete=models.CASCADE, related_name='view_count')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = '記事の閲覧カウント'
        db_table = 'view_count'
        indexes = [
            models.Index(fields=['article', 'created_at']),
        ]

    @classmethod
    def create_view_count(cls, user, article):
        if user != article.author:
            # 存在していなかったら新規で作成し、存在していたらレコードを返す
            cls.objects.get_or_create(user=user, article=article)
        view_count = cls.objects.filter(article=article).count()
        return view_count


class Follow(models.Model):
    follower = models.ForeignKey(get_user_model(), verbose_name="フォローしたユーザー", related_name='following', on_delete=models.CASCADE)
    followed = models.ForeignKey(get_user_model(), verbose_name="フォローされたユーザー", related_name='followers', on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)

    class Meta:
        verbose_name_plural = 'フォロー'
        db_table = 'user_follow'
        unique_together = ('follower', 'followed')

    # def __init__(self):
    #     return f'{self.follower} follows {self.followed}'

blog/forms.py
from django import forms

from .models import Comment, Article, ArticleTag

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'comment',
        )

class ArticleNewForm(forms.ModelForm):
    # 新たにtagsを定義（理由：勝手にchoiceFieldにされるから）
    # ?リンク先 https://zenn.dev/cococig/articles/d3374aa8fd70b0

    tags = forms.CharField(label="タグ", max_length=250, required=False)

    class Meta:
        model = Article
        fields = (
            'title',
            'text',
            'is_public',
            'sell_flag',
            'price',
        )

    def clean_tags(self):
        # is_valid()が呼び出された時に処理が走る
        tags = self.cleaned_data['tags']
        # カンマで区切られたタグをリストに変換
        tag_list = [tag.strip() for tag in tags.split('、') if tag.strip()]

        # 処理が終わったらself.cleaned_data['tags']に自動的に入れてくれる
        return tag_list

    def save(self, author, commit=True):
        article = super().save(commit=False)

        article.author = author
        article.save()
        for tag_name in self.cleaned_data['tags']:
            slug = tag_name.lower().replace(' ', '-')
            tag, created = ArticleTag.objects.get_or_create(slug=slug, defaults={'name': tag_name})
            article.tags.add(tag)
        return article

mysite/views.py
import os

from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.views import View
from django.contrib import messages
from django.contrib.auth import login
from django.core.mail import send_mail
from django.db.models import Count

from blog.models import *
from mysite.forms import UserCreateForm, ProfileForm
from common.myiste_def import *
from mysite.models.profile_models import PREFECTURE_CHOICE


class TopView(View):
    template_name = 'mysite/top.html'

    def get(self, request, *args, **kwargs):
        # 人気記事TOP3を取得
        popular_articles = Article.objects.filter(is_public=True).annotate(
            like_count=Count('article_like'),
            comment_count=Count('comments'),
            view_total_count=Count('view_count'),
            ).order_by('-like_count')[:4]

        # 決済未完了のorderを取得
        orders = Order.objects.filter(user=request.user, order_status=0)

        # タプルの内容をflat=Trueでリスト形式に変更
        purchased_article_ids = orders.values_list('article_id', flat=True)

        # UserItemが存在していたら購入扱いにする
        user_items = user_item_index(request, request.user, 1)
        uset_item_ids = user_items.values_list('article_id', flat=True)

        return render(request, self.template_name, {
            'title': 'Really Site',
            'popular_articles': popular_articles,
            'purchased_article_ids': purchased_article_ids,
            'uset_item_ids': uset_item_ids,
        })


class Login(LoginView):
    template_name = 'mysite/auth.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, f'すでに{request.user}でログインしています。')
            return redirect('/')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, 'ログインしました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'ユーザー名またはパスワードが間違っています。')
        return super().form_invalid(form)


class Signup(View):
    template_name = 'mysite/auth.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, f'すでに{request.user}でログインしています。')
            return redirect('/')

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        signup_btn = 'サインイン'
        return render(request, self.template_name, {
            'signup_btn': signup_btn,
        })

    def post(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.is_active = False
            user.save()
            # ログインさせる
            login(request, user)
            messages.success(request, 'ユーザー登録が完了しました。')
            return redirect('/')
        else:
            messages.error(request, 'ユーザー登録に失敗しました。（既に同じメールアドレスを持ったユーザーが存在します。）')
            return redirect('signup')


class MypageView(CustomLoginRequiredMixin, View):
    template_name = 'mysite/mypage.html'

    def get(self, request, *args, **kwargs):
        false_public_artiles = Article.objects.filter(author=request.user, is_public=False).annotate(
            like_count=Count('article_like'),
            comment_count=Count('comments'),
            view_total_count=Count('view_count'),
        )

        true_public_artiles = Article.objects.filter(author=request.user, is_public=True).annotate(
            like_count=Count('article_like'),
            comment_count=Count('comments'),
            view_total_count=Count('view_count'),
        )

        follows_count = request.user.profile.follows.count()
        followed_count = request.user.followed_by.count()

        return render(request, self.template_name, {
            'prefecture_choices': PREFECTURE_CHOICE,
            'false_public_artiles': false_public_artiles,
            'true_public_artiles': true_public_artiles,
            'follows_count': follows_count,
            'followed_count': followed_count,
        })

    def post(self, request, *args, **kwargs):
        profile_form = ProfileForm(request.POST, request.FILES)
        user_image = request.user.profile.image.url

        if profile_form.is_valid():
            profile = profile_form.save(user_image, commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'プロフィール情報が更新されました。')
        else:
            messages.error(request, 'プロフィール情報が更新できませんでした。')
            return redirect('mypage')

        return redirect('mypage')


class AuthorView(CustomLoginRequiredMixin, View):
    template_name = 'mysite/author.html'

    def get(self, request, pk, *args, **kwargs):
        try:
            User = get_user_model()
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            messages.error(request, '存在しないユーザーです。')
            return redirect('/')

        # 投稿主だったらマイページへ遷移させる
        if request.user == user:
            return redirect('mypage')

        public_artiles = Article.objects.filter(author=request.user, is_public=True).annotate(
            like_count=Count('article_like'),
            comment_count=Count('comments'),
            view_total_count=Count('view_count'),
        )

        # フォローしているか？
        try:
            follow = Follow.objects.get(follower=request.user, followed=user)
        except Follow.DoesNotExist:
            follow = False

        follows_count = user.profile.follows.all().count()
        # followed_byはUserモデルに適用される（逆参照）
        followed_count = user.followed_by.all().count()

        return render(request, self.template_name, {
            'user': user,
            'public_artiles': public_artiles,
            'follow': follow,
            'follows_count': follows_count,
            'followed_count': followed_count,
        })


class ContactView(View):
    template_name = 'mysite/contact.html'

    def get(self, request, *args, **kwargs):

        return render(request, self.template_name, {
        })

    def post(self, request, *args, **kwargs):
        print(request.POST.get)
        # ------ email送信
        subject = 'お問い合わせがありました。'
        message = "お問い合わせがありました。\n\n名前: {}\nメールアドレス: {}\n内容: {}\n".format(
            request.POST.get('name'),
            request.POST.get('email'),
            request.POST.get('contact'),
        )
        email_from = os.environ['EMAIL_HOST_USER']
        email_to = [os.environ['EMAIL_HOST_USER'], ]
        try:
            send_mail(subject, message, email_from, email_to)
            messages.success(request, 'お問い合わせメールの送信をしました。')
        except Exception as e:
            messages.error(request, f'メールの送信に失敗しました。エラーコード{e}')
            return redirect('/')
        return render(request, self.template_name, {
        })

templates/mysite/blog/article.html
{% extends "mysite/base.html" %}
{% load cache %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">

            {% comment %} {% cache 86400 article article.id %} {% endcomment %}
            {% comment %} カルセール {% endcomment %}
            <div id="carouselIndicators{{ article.id }}" class="carousel slide carousel-fade col-10" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    {% for / in article.image.all %}
                    <button type="button" data-bs-target="#carouselIndicators{{ article.id }}" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %} pt-1" aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}"></button>
                    {% endfor %}
                </div>
                <div class="carousel-inner">
                    {% for image in article.image.all %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="10000000000">
                        <img src="/media/{{ image.image }}" class="w-100 article_image img-thumbnail" alt="...">
                    </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators{{ article.id }}" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon btn btn-outline-dark rounded-circle p-4" aria-hidden="true"></span>
                    <span class="visually-hidden"></span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators{{ article.id }}" data-bs-slide="next">
                    <span class="carousel-control-next-icon btn btn-outline-dark rounded-circle p-4" aria-hidden="true"></span>
                    <span class="visually-hidden"></span>
                </button>
            </div>
            {% comment %} カルセールここまで {% endcomment %}
            <div class="d-flex mb-2 mt-2">
                <img src="{{ article.author.profile.image.url }}" alt="" class="article_profile_image rounded-circle border border-secondary">
                <h5 class="mt-1 ms-2">{{ article.author.profile.username }}</h5>
            </div>
            <h3 class="display-5 font-italic">
                {{ article.title }}
            </h3>
            <p>{{ article.text }}</p>
            {% comment %} {% endcache %} {% endcomment %}
            {% include "snippets/like.html" %}
            <div class="mt-2 me-2">
                {% for tag in article.tags.all %}
                    <a href="{% url 'blog:tag_detail' name=tag.name %}" class="btn btn-sm btn-outline-secondary">
                        <i class="bi bi-tag"></i>{{ tag.name }}
                    </a>
                {% endfor %}
            </div>
            <div class="mt-3 small text-muted">
                閲覧数 : {{ view_count }}
            </div>
            <div class="mt-1 small text-secondary">
                {% if article.sell_flag and article.price != 0 %}
                記事を販売中：価格{{ article.price }}円
                {% else %}
                無料
                {% endif %}
            </div>
            <p class="small text-muted text-right mt-1">
                {{ article.created_at }}
                {% if article.is_public %}
                    公開中
                {% else %}
                    非公開中
                {% endif %}
                {% if request.user == article.author %}
                <a href="{% url 'blog:edit' article.id %}" class="btn btn-info">編集</a>
                <a href="{% url 'blog:delete' article.id %}" class="btn btn-danger ms-3" onclick="return delete_article_alert(this);">削除</a>
                {% endif %}
            </p>

            <hr class="my-2">
            {% comment %} コメント機能 {% endcomment %}
            {% include "snippets/comment.html" %}
        </div>

        {% comment %} サイドバー {% endcomment %}
        <aside class="col-md-4">
            <div class="p-4 mb-3 bg-light rounded">
                <h4 class="font-italic">
                    ふじサンについて
                </h4>
                <p class="mb-0">ようこそMy講座へ！</p>
            </div>
        </aside>

    </div>
</main>

<script>
    function delete_article_alert(node) {
        return confirm('記事を削除してもよろしいでしょうか？');
    }
</script>

{% endblock %}

templates/mysite/blog/blog_new.html
{% extends "mysite/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <h3 class="text-center">{{ title }}</h3>
        <div class="col-lg-10 col-md-12 m-auto">
            <form action="{{ request.path }}" method="post" enctype='multipart/form-data' class="needs-validated">
                {% csrf_token %}

                <div class="error-messages">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item text-danger">{{ article_new_form.errors }}</li>
                    </ul>
                </div>

                <div class="mb-3">
                    {% if title == 'ブログ編集' %}
                        <label for="InputImage" class="form-label">現在の投稿画像</label>
                        <div class="row">
                            {% for image in article.image.all %}
                            <div class="col-lg-4 col-md-6 col-12 mb-3">
                                <img src="/media/{{ image.image }}" alt="現在の画像" class="img-thumbnail h-100 w-100" width="200px">
                            </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <label for="InputImage" class="form-label">投稿画像</label>
                    {% if title == 'ブログ編集' %}
                        <input type="file" accept='image/*' name="images" class="form-control" id="InputImage" autofocus multiple>
                    {% else %}
                        <input type="file" accept='image/*' name="images" class="form-control" id="InputImage" required utofocus multiple>
                        <div class="invalid-feedback">画像を1枚以上選択してください</div>
                        {% if image_error %}
                        <small class="text-danger mt-2 ms-1">{{ image_error }}</small>
                        {% endif %}
                        {% endif %}
                    </div>

                <div class="mb-3">
                    <label for="InputTitle" class="form-label">タイトル</label>
                    <input type="text" name="title" class="form-control" id="InputTitle" placeholder="タイトル" value="{{ article_title }}" required>
                    <div class="invalid-feedback">タイトルを入力してください</div>
                </div>

                <div class="mb-3">
                    <label class="form-label">テキスト</label>
                    <textarea class="form-control" id='id_text' name="text" rows='4' required>{{ article_text|default:'' }}</textarea>
                    <div class="invalid-feedback">テキストを入力してください</div>
                </div>

                <div class="mb-3">
                    <label for="InputTags" class="form-label">タグ</label>
                    <input type="text" name="tags" class="form-control" id="InputTags" aria-describedby="tagsHelp" placeholder="タグ" value="{{ tags }}">
                    <div id="tagsHelp" class="form-text">カンマ区切りでタグを入力してください</div>
                </div>

                <div class="mb-3 form-check">
                    <input type="hidden" name='is_public' value=false>
                    <input type="checkbox" class="form-check-input" id="IsPpublicCheck" name='is_public' value="1" {% if article_is_public %}checked{% else %}off{% endif %}>
                    <label class="form-check-label" for="IsPpublicCheck">公開しますか？</label>
                </div>

                <div class="mb-3 form-check">
                    <input type="hidden" name='sell_flag' value=false>
                    <input type="checkbox" class="form-check-input" id="SellFlagCheck" name='sell_flag' value="1" {% if article_sell_flag %}checked{% endif %}>
                    <label class="form-check-label" for="SellFlagCheck">記事を有料コンテンツ化しますか？</label>
                </div>

                <div class="mb-3" id="priceInputContainer" style="display: none;">
                    <label for="InputPrice" class="form-label">金額</label>
                    <input type="number" name="price" class="form-control" id="InputPrice" placeholder="金額" value="{{ article_price }}" aria-describedby="priceHelp">
                    <div id="priceHelp" class="form-text">500円の場合は「500」と入力</div>
                </div>

                <button type="submit" class="btn btn-primary">保存</button>
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const sellFlagCheck = document.getElementById('SellFlagCheck');
        const priceInputContainer = document.getElementById('priceInputContainer');
        const priceInput = document.getElementById('InputPrice');

        function togglePriceInput() {
            if (sellFlagCheck.checked) {
                priceInputContainer.style.display = 'block';
                priceInput.required = true;
            } else {
                priceInputContainer.style.display = 'none';
                priceInput.value = "";
                priceInput.required = false;
            }
        }

        sellFlagCheck.addEventListener('change', togglePriceInput);

        // 初期状態を設定（ページ読み込み時やフォーム編集時に使用）
        togglePriceInput();
    });
    </script>
{% endblock %}

templates/mysite/blog/blogs.html
{% extends "mysite/base.html" %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="pb-4 font-italic border-bottom">
                {{ page_title }}
            </h3>

            <div class="card-deck row row-cols-1 row-cols-md-2 g-4">
                {% for article in paginator_articles %}
                <div class="col-lg-6 col">
                    {% include "snippets/articles_index.html" %}
                </div>
                {% endfor %}
            </div>

            {% comment %} ページネーション {% endcomment %}
            {% include "snippets/pagination.html" %}
        </div>
        {% comment %} サイドバー {% endcomment %}
        {% include "snippets/sideber.html" %}
    </div>
</main>

{% endblock %}